/*
 iScroll v5.2.0-snapshot ~ (c) 2008-2017 Matteo Spinelli ~ http://cubiq.org/license */
(function(k,m,e){function q(a,b){this.wrapper="string"==typeof a?m.querySelector(a):a;this.scroller=this.wrapper.children[0];this.scrollerStyle=this.scroller.style;this.options={resizeScrollbars:!0,mouseWheelSpeed:20,snapThreshold:.334,disablePointer:!c.hasPointer,disableTouch:c.hasPointer||!c.hasTouch,disableMouse:c.hasPointer||c.hasTouch,startX:0,startY:0,scrollY:!0,directionLockThreshold:5,momentum:!0,bounce:!0,bounceTime:600,bounceEasing:"",preventDefault:!0,preventDefaultException:{tagName:/^(INPUT|TEXTAREA|BUTTON|SELECT)$/},
HWCompositing:!0,useTransition:!0,useTransform:!0,bindToWrapper:"undefined"===typeof k.onmousedown};for(var f in b)this.options[f]=b[f];this.translateZ=this.options.HWCompositing&&c.hasPerspective?" translateZ(0)":"";this.options.useTransition=c.hasTransition&&this.options.useTransition;this.options.useTransform=c.hasTransform&&this.options.useTransform;this.options.eventPassthrough=!0===this.options.eventPassthrough?"vertical":this.options.eventPassthrough;this.options.preventDefault=!this.options.eventPassthrough&&
this.options.preventDefault;this.options.scrollY="vertical"==this.options.eventPassthrough?!1:this.options.scrollY;this.options.scrollX="horizontal"==this.options.eventPassthrough?!1:this.options.scrollX;this.options.freeScroll=this.options.freeScroll&&!this.options.eventPassthrough;this.options.directionLockThreshold=this.options.eventPassthrough?0:this.options.directionLockThreshold;this.options.bounceEasing="string"==typeof this.options.bounceEasing?c.ease[this.options.bounceEasing]||c.ease.circular:
this.options.bounceEasing;this.options.resizePolling=void 0===this.options.resizePolling?60:this.options.resizePolling;!0===this.options.tap&&(this.options.tap="tap");this.options.useTransition||this.options.useTransform||/relative|absolute/i.test(this.scrollerStyle.position)||(this.scrollerStyle.position="relative");"scale"==this.options.shrinkScrollbars&&(this.options.useTransition=!1);this.options.invertWheelDirection=this.options.invertWheelDirection?-1:1;this.directionY=this.directionX=this.y=
this.x=0;this._events={};this._init();this.refresh();this.scrollTo(this.options.startX,this.options.startY);this.enable()}function t(a,b,f){var d=m.createElement("div"),c=m.createElement("div");!0===f&&(d.style.cssText="position:absolute;z-index:9999",c.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;position:absolute;background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.9);border-radius:3px");c.className="iScrollIndicator";"h"==a?(!0===f&&(d.style.cssText+=
";height:7px;left:2px;right:2px;bottom:0",c.style.height="100%"),d.className="iScrollHorizontalScrollbar"):(!0===f&&(d.style.cssText+=";width:7px;bottom:2px;top:2px;right:1px",c.style.width="100%"),d.className="iScrollVerticalScrollbar");d.style.cssText+=";overflow:hidden";b||(d.style.pointerEvents="none");d.appendChild(c);return d}function u(a,b){this.wrapper="string"==typeof b.el?m.querySelector(b.el):b.el;this.wrapperStyle=this.wrapper.style;this.indicator=this.wrapper.children[0];this.indicatorStyle=
this.indicator.style;this.scroller=a;this.options={listenX:!0,listenY:!0,interactive:!1,resize:!0,defaultScrollbars:!1,shrink:!1,fade:!1,speedRatioX:0,speedRatioY:0};for(var f in b)this.options[f]=b[f];this.sizeRatioY=this.sizeRatioX=1;this.maxPosY=this.maxPosX=0;this.options.interactive&&(this.options.disableTouch||(c.addEvent(this.indicator,"touchstart",this),c.addEvent(k,"touchend",this)),this.options.disablePointer||(c.addEvent(this.indicator,c.prefixPointerEvent("pointerdown"),this),c.addEvent(k,
c.prefixPointerEvent("pointerup"),this)),this.options.disableMouse||(c.addEvent(this.indicator,"mousedown",this),c.addEvent(k,"mouseup",this)));if(this.options.fade){this.wrapperStyle[c.style.transform]=this.scroller.translateZ;var d=c.style.transitionDuration;if(d){this.wrapperStyle[d]=c.isBadAndroid?"0.0001ms":"0ms";var e=this;c.isBadAndroid&&r(function(){"0.0001ms"===e.wrapperStyle[d]&&(e.wrapperStyle[d]="0s")});this.wrapperStyle.opacity="0"}}}var r=k.requestAnimationFrame||k.webkitRequestAnimationFrame||
k.mozRequestAnimationFrame||k.oRequestAnimationFrame||k.msRequestAnimationFrame||function(a){k.setTimeout(a,1E3/60)},c=function(){function a(a){return!1===c?!1:""===c?a:c+a.charAt(0).toUpperCase()+a.substr(1)}var b={},f=m.createElement("div").style,c=function(){for(var a=["t","webkitT","MozT","msT","OT"],b,c=0,d=a.length;c<d;c++)if(b=a[c]+"ransform",b in f)return a[c].substr(0,a[c].length-1);return!1}();b.getTime=Date.now||function(){return(new Date).getTime()};b.extend=function(a,b){for(var h in b)a[h]=
b[h]};b.addEvent=function(a,b,c,f){a.addEventListener(b,c,!!f)};b.removeEvent=function(a,b,c,f){a.removeEventListener(b,c,!!f)};b.prefixPointerEvent=function(a){return k.MSPointerEvent?"MSPointer"+a.charAt(7).toUpperCase()+a.substr(8):a};b.momentum=function(a,b,c,f,d,g){b=a-b;c=e.abs(b)/c;var h;g=void 0===g?6E-4:g;h=a+c*c/(2*g)*(0>b?-1:1);g=c/g;h<f?(h=d?f-d/2.5*(c/8):f,b=e.abs(h-a),g=b/c):0<h&&(h=d?d/2.5*(c/8):0,b=e.abs(a)+h,g=b/c);return{destination:e.round(h),duration:g}};var g=a("transform");b.extend(b,
{hasTransform:!1!==g,hasPerspective:a("perspective")in f,hasTouch:"ontouchstart"in k,hasPointer:!(!k.PointerEvent&&!k.MSPointerEvent),hasTransition:a("transition")in f});b.isBadAndroid=function(){var a=k.navigator.appVersion;return/Android/.test(a)&&!/Chrome\/\d/.test(a)?(a=a.match(/Safari\/(\d+.\d)/))&&"object"===typeof a&&2<=a.length?535.19>parseFloat(a[1]):!0:!1}();b.extend(b.style={},{transform:g,transitionTimingFunction:a("transitionTimingFunction"),transitionDuration:a("transitionDuration"),
transitionDelay:a("transitionDelay"),transformOrigin:a("transformOrigin"),touchAction:a("touchAction")});b.hasClass=function(a,b){return(new RegExp("(^|\\s)"+b+"(\\s|$)")).test(a.className)};b.addClass=function(a,c){if(!b.hasClass(a,c)){var f=a.className.split(" ");f.push(c);a.className=f.join(" ")}};b.removeClass=function(a,c){b.hasClass(a,c)&&(a.className=a.className.replace(new RegExp("(^|\\s)"+c+"(\\s|$)","g")," "))};b.offset=function(a){for(var b=-a.offsetLeft,c=-a.offsetTop;a=a.offsetParent;)b-=
a.offsetLeft,c-=a.offsetTop;return{left:b,top:c}};b.preventDefaultException=function(a,b){for(var c in b)if(b[c].test(a[c]))return!0;return!1};b.extend(b.eventType={},{touchstart:1,touchmove:1,touchend:1,mousedown:2,mousemove:2,mouseup:2,pointerdown:3,pointermove:3,pointerup:3,MSPointerDown:3,MSPointerMove:3,MSPointerUp:3});b.extend(b.ease={},{quadratic:{style:"cubic-bezier(0.25, 0.46, 0.45, 0.94)",fn:function(a){return a*(2-a)}},circular:{style:"cubic-bezier(0.1, 0.57, 0.1, 1)",fn:function(a){return e.sqrt(1-
--a*a)}},back:{style:"cubic-bezier(0.175, 0.885, 0.32, 1.275)",fn:function(a){return--a*a*(5*a+4)+1}},bounce:{style:"",fn:function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375}},elastic:{style:"",fn:function(a){return 0===a?0:1==a?1:.4*e.pow(2,-10*a)*e.sin(2*(a-.055)*e.PI/.22)+1}}});b.tap=function(a,b){var c=m.createEvent("Event");c.initEvent(b,!0,!0);c.pageX=a.pageX;c.pageY=a.pageY;a.target.dispatchEvent(c)};
b.click=function(a){var b=a.target,c;/(SELECT|INPUT|TEXTAREA)/i.test(b.tagName)||(c=m.createEvent(k.MouseEvent?"MouseEvents":"Event"),c.initEvent("click",!0,!0),c.view=a.view||k,c.detail=1,c.screenX=b.screenX||0,c.screenY=b.screenY||0,c.clientX=b.clientX||0,c.clientY=b.clientY||0,c.ctrlKey=!!a.ctrlKey,c.altKey=!!a.altKey,c.shiftKey=!!a.shiftKey,c.metaKey=!!a.metaKey,c.button=0,c.relatedTarget=null,c._constructed=!0,b.dispatchEvent(c))};b.getTouchAction=function(a,b){var c="none";"vertical"===a?c=
"pan-y":"horizontal"===a&&(c="pan-x");b&&"none"!=c&&(c+=" pinch-zoom");return c};b.getRect=function(a){return a instanceof SVGElement?(a=a.getBoundingClientRect(),{top:a.top,left:a.left,width:a.width,height:a.height}):{top:a.offsetTop,left:a.offsetLeft,width:a.offsetWidth,height:a.offsetHeight}};return b}();q.prototype={version:"5.2.0-snapshot",_init:function(){this._initEvents();(this.options.scrollbars||this.options.indicators)&&this._initIndicators();this.options.mouseWheel&&this._initWheel();
this.options.snap&&this._initSnap();this.options.keyBindings&&this._initKeys()},destroy:function(){this._initEvents(!0);clearTimeout(this.resizeTimeout);this.resizeTimeout=null;this._execEvent("destroy")},_transitionEnd:function(a){a.target==this.scroller&&this.isInTransition&&(this._transitionTime(),this.resetPosition(this.options.bounceTime)||(this.isInTransition=!1,this._execEvent("scrollEnd")))},_start:function(a){if(!(1!=c.eventType[a.type]&&0!==(a.which?a.button:2>a.button?0:4==a.button?1:2)||
!this.enabled||this.initiated&&c.eventType[a.type]!==this.initiated)){!this.options.preventDefault||c.isBadAndroid||c.preventDefaultException(a.target,this.options.preventDefaultException)||a.preventDefault();var b=a.touches?a.touches[0]:a;this.initiated=c.eventType[a.type];this.moved=!1;this.directionLocked=this.directionY=this.directionX=this.distY=this.distX=0;this.startTime=c.getTime();this.options.useTransition&&this.isInTransition?(this._transitionTime(),this.isInTransition=!1,a=this.getComputedPosition(),
this._translate(e.round(a.x),e.round(a.y)),this._execEvent("scrollEnd")):!this.options.useTransition&&this.isAnimating&&(this.isAnimating=!1,this._execEvent("scrollEnd"));this.startX=this.x;this.startY=this.y;this.absStartX=this.x;this.absStartY=this.y;this.pointX=b.pageX;this.pointY=b.pageY;this._execEvent("beforeScrollStart")}},_move:function(a){if(this.enabled&&c.eventType[a.type]===this.initiated){this.options.preventDefault&&a.preventDefault();var b=a.touches?a.touches[0]:a,f=b.pageX-this.pointX,
d=b.pageY-this.pointY,g=c.getTime(),h;this.pointX=b.pageX;this.pointY=b.pageY;this.distX+=f;this.distY+=d;b=e.abs(this.distX);h=e.abs(this.distY);if(!(300<g-this.endTime&&10>b&&10>h)){this.directionLocked||this.options.freeScroll||(this.directionLocked=b>h+this.options.directionLockThreshold?"h":h>=b+this.options.directionLockThreshold?"v":"n");if("h"==this.directionLocked){if("vertical"==this.options.eventPassthrough)a.preventDefault();else if("horizontal"==this.options.eventPassthrough){this.initiated=
!1;return}d=0}else if("v"==this.directionLocked){if("horizontal"==this.options.eventPassthrough)a.preventDefault();else if("vertical"==this.options.eventPassthrough){this.initiated=!1;return}f=0}f=this.hasHorizontalScroll?f:0;d=this.hasVerticalScroll?d:0;a=this.x+f;b=this.y+d;if(0<a||a<this.maxScrollX)a=this.options.bounce?this.x+f/3:0<a?0:this.maxScrollX;if(0<b||b<this.maxScrollY)b=this.options.bounce?this.y+d/3:0<b?0:this.maxScrollY;this.directionX=0<f?-1:0>f?1:0;this.directionY=0<d?-1:0>d?1:0;
this.moved||this._execEvent("scrollStart");this.moved=!0;this._translate(a,b);300<g-this.startTime&&(this.startTime=g,this.startX=this.x,this.startY=this.y)}}},_end:function(a){if(this.enabled&&c.eventType[a.type]===this.initiated){this.options.preventDefault&&!c.preventDefaultException(a.target,this.options.preventDefaultException)&&a.preventDefault();var b,f;f=c.getTime()-this.startTime;var d=e.round(this.x),g=e.round(this.y),h=e.abs(d-this.startX),k=e.abs(g-this.startY);b=0;var l="";this.initiated=
this.isInTransition=0;this.endTime=c.getTime();if(!this.resetPosition(this.options.bounceTime))if(this.scrollTo(d,g),this.moved)if(this._events.flick&&200>f&&100>h&&100>k)this._execEvent("flick");else if(this.options.momentum&&300>f&&(b=this.hasHorizontalScroll?c.momentum(this.x,this.startX,f,this.maxScrollX,this.options.bounce?this.wrapperWidth:0,this.options.deceleration):{destination:d,duration:0},f=this.hasVerticalScroll?c.momentum(this.y,this.startY,f,this.maxScrollY,this.options.bounce?this.wrapperHeight:
0,this.options.deceleration):{destination:g,duration:0},d=b.destination,g=f.destination,b=e.max(b.duration,f.duration),this.isInTransition=1),this.options.snap&&(this.currentPage=l=this._nearestSnap(d,g),b=this.options.snapSpeed||e.max(e.max(e.min(e.abs(d-l.x),1E3),e.min(e.abs(g-l.y),1E3)),300),d=l.x,g=l.y,this.directionY=this.directionX=0,l=this.options.bounceEasing),d!=this.x||g!=this.y){if(0<d||d<this.maxScrollX||0<g||g<this.maxScrollY)l=c.ease.quadratic;this.scrollTo(d,g,b,l)}else this._execEvent("scrollEnd");
else this.options.tap&&c.tap(a,this.options.tap),this.options.click&&c.click(a),this._execEvent("scrollCancel")}},_resize:function(){var a=this;clearTimeout(this.resizeTimeout);this.resizeTimeout=setTimeout(function(){a.refresh()},this.options.resizePolling)},resetPosition:function(a){var b=this.x,c=this.y;!this.hasHorizontalScroll||0<this.x?b=0:this.x<this.maxScrollX&&(b=this.maxScrollX);!this.hasVerticalScroll||0<this.y?c=0:this.y<this.maxScrollY&&(c=this.maxScrollY);if(b==this.x&&c==this.y)return!1;
this.scrollTo(b,c,a||0,this.options.bounceEasing);return!0},disable:function(){this.enabled=!1},enable:function(){this.enabled=!0},refresh:function(){c.getRect(this.wrapper);this.wrapperWidth=this.wrapper.clientWidth;this.wrapperHeight=this.wrapper.clientHeight;var a=c.getRect(this.scroller);this.scrollerWidth=a.width;this.scrollerHeight=a.height;this.maxScrollX=this.wrapperWidth-this.scrollerWidth;this.maxScrollY=this.wrapperHeight-this.scrollerHeight;this.hasHorizontalScroll=this.options.scrollX&&
0>this.maxScrollX;this.hasVerticalScroll=this.options.scrollY&&0>this.maxScrollY;this.hasHorizontalScroll||(this.maxScrollX=0,this.scrollerWidth=this.wrapperWidth);this.hasVerticalScroll||(this.maxScrollY=0,this.scrollerHeight=this.wrapperHeight);this.directionY=this.directionX=this.endTime=0;c.hasPointer&&!this.options.disablePointer&&(this.wrapper.style[c.style.touchAction]=c.getTouchAction(this.options.eventPassthrough,!0),this.wrapper.style[c.style.touchAction]||(this.wrapper.style[c.style.touchAction]=
c.getTouchAction(this.options.eventPassthrough,!1)));this.wrapperOffset=c.offset(this.wrapper);this._execEvent("refresh");this.resetPosition()},on:function(a,b){this._events[a]||(this._events[a]=[]);this._events[a].push(b)},off:function(a,b){this._events[a]&&(b=this._events[a].indexOf(b),-1<b&&this._events[a].splice(b,1))},_execEvent:function(a){if(this._events[a]){var b=0,c=this._events[a].length;if(c)for(;b<c;b++)this._events[a][b].apply(this,[].slice.call(arguments,1))}},scrollBy:function(a,b,
c,d){a=this.x+a;b=this.y+b;this.scrollTo(a,b,c||0,d)},scrollTo:function(a,b,f,d){d=d||c.ease.circular;this.isInTransition=this.options.useTransition&&0<f;var e=this.options.useTransition&&d.style;!f||e?(e&&(this._transitionTimingFunction(d.style),this._transitionTime(f)),this._translate(a,b)):this._animate(a,b,f,d.fn)},scrollToElement:function(a,b,f,d,g){if(a=a.nodeType?a:this.scroller.querySelector(a)){var h=c.offset(a);h.left-=this.wrapperOffset.left;h.top-=this.wrapperOffset.top;a=c.getRect(a);
var k=c.getRect(this.wrapper);!0===f&&(f=e.round(a.width/2-k.width/2));!0===d&&(d=e.round(a.height/2-k.height/2));h.left-=f||0;h.top-=d||0;h.left=0<h.left?0:h.left<this.maxScrollX?this.maxScrollX:h.left;h.top=0<h.top?0:h.top<this.maxScrollY?this.maxScrollY:h.top;b=void 0===b||null===b||"auto"===b?e.max(e.abs(this.x-h.left),e.abs(this.y-h.top)):b;this.scrollTo(h.left,h.top,b,g)}},_transitionTime:function(a){if(this.options.useTransition){a=a||0;var b=c.style.transitionDuration;if(b){this.scrollerStyle[b]=
a+"ms";if(!a&&c.isBadAndroid){this.scrollerStyle[b]="0.0001ms";var f=this;r(function(){"0.0001ms"===f.scrollerStyle[b]&&(f.scrollerStyle[b]="0s")})}if(this.indicators)for(var d=this.indicators.length;d--;)this.indicators[d].transitionTime(a)}}},_transitionTimingFunction:function(a){this.scrollerStyle[c.style.transitionTimingFunction]=a;if(this.indicators)for(var b=this.indicators.length;b--;)this.indicators[b].transitionTimingFunction(a)},_translate:function(a,b){this.options.useTransform?this.scrollerStyle[c.style.transform]=
"translate("+a+"px,"+b+"px)"+this.translateZ:(a=e.round(a),b=e.round(b),this.scrollerStyle.left=a+"px",this.scrollerStyle.top=b+"px");this.x=a;this.y=b;if(this.indicators)for(a=this.indicators.length;a--;)this.indicators[a].updatePosition()},_initEvents:function(a){a=a?c.removeEvent:c.addEvent;var b=this.options.bindToWrapper?this.wrapper:k;a(k,"orientationchange",this);a(k,"resize",this);this.options.click&&a(this.wrapper,"click",this,!0);this.options.disableMouse||(a(this.wrapper,"mousedown",this),
a(b,"mousemove",this),a(b,"mousecancel",this),a(b,"mouseup",this));c.hasPointer&&!this.options.disablePointer&&(a(this.wrapper,c.prefixPointerEvent("pointerdown"),this),a(b,c.prefixPointerEvent("pointermove"),this),a(b,c.prefixPointerEvent("pointercancel"),this),a(b,c.prefixPointerEvent("pointerup"),this));c.hasTouch&&!this.options.disableTouch&&(a(this.wrapper,"touchstart",this),a(b,"touchmove",this),a(b,"touchcancel",this),a(b,"touchend",this));a(this.scroller,"transitionend",this);a(this.scroller,
"webkitTransitionEnd",this);a(this.scroller,"oTransitionEnd",this);a(this.scroller,"MSTransitionEnd",this)},getComputedPosition:function(){var a=k.getComputedStyle(this.scroller,null),b;this.options.useTransform?(a=a[c.style.transform].split(")")[0].split(", "),b=+(a[12]||a[4]),a=+(a[13]||a[5])):(b=+a.left.replace(/[^-\d.]/g,""),a=+a.top.replace(/[^-\d.]/g,""));return{x:b,y:a}},_initIndicators:function(){function a(a){if(h.indicators)for(var b=h.indicators.length;b--;)a.call(h.indicators[b])}var b=
this.options.interactiveScrollbars,c="string"!=typeof this.options.scrollbars,d=[],e,h=this;this.indicators=[];this.options.scrollbars&&(this.options.scrollY&&(e={el:t("v",b,this.options.scrollbars),interactive:b,defaultScrollbars:!0,customStyle:c,resize:this.options.resizeScrollbars,shrink:this.options.shrinkScrollbars,fade:this.options.fadeScrollbars,listenX:!1},this.wrapper.appendChild(e.el),d.push(e)),this.options.scrollX&&(e={el:t("h",b,this.options.scrollbars),interactive:b,defaultScrollbars:!0,
customStyle:c,resize:this.options.resizeScrollbars,shrink:this.options.shrinkScrollbars,fade:this.options.fadeScrollbars,listenY:!1},this.wrapper.appendChild(e.el),d.push(e)));this.options.indicators&&(d=d.concat(this.options.indicators));for(b=d.length;b--;)this.indicators.push(new u(this,d[b]));this.options.fadeScrollbars&&(this.on("scrollEnd",function(){a(function(){this.fade()})}),this.on("scrollCancel",function(){a(function(){this.fade()})}),this.on("scrollStart",function(){a(function(){this.fade(1)})}),
this.on("beforeScrollStart",function(){a(function(){this.fade(1,!0)})}));this.on("refresh",function(){a(function(){this.refresh()})});this.on("destroy",function(){a(function(){this.destroy()});delete this.indicators})},_initWheel:function(){c.addEvent(this.wrapper,"wheel",this);c.addEvent(this.wrapper,"mousewheel",this);c.addEvent(this.wrapper,"DOMMouseScroll",this);this.on("destroy",function(){clearTimeout(this.wheelTimeout);this.wheelTimeout=null;c.removeEvent(this.wrapper,"wheel",this);c.removeEvent(this.wrapper,
"mousewheel",this);c.removeEvent(this.wrapper,"DOMMouseScroll",this)})},_wheel:function(a){if(this.enabled){a.preventDefault();var b,c,d,g=this;void 0===this.wheelTimeout&&g._execEvent("scrollStart");clearTimeout(this.wheelTimeout);this.wheelTimeout=setTimeout(function(){g.options.snap||g._execEvent("scrollEnd");g.wheelTimeout=void 0},400);if("deltaX"in a)1===a.deltaMode?(b=-a.deltaX*this.options.mouseWheelSpeed,a=-a.deltaY*this.options.mouseWheelSpeed):(b=-a.deltaX,a=-a.deltaY);else if("wheelDeltaX"in
a)b=a.wheelDeltaX/120*this.options.mouseWheelSpeed,a=a.wheelDeltaY/120*this.options.mouseWheelSpeed;else if("wheelDelta"in a)b=a=a.wheelDelta/120*this.options.mouseWheelSpeed;else if("detail"in a)b=a=-a.detail/3*this.options.mouseWheelSpeed;else return;b*=this.options.invertWheelDirection;a*=this.options.invertWheelDirection;this.hasVerticalScroll||(b=a,a=0);this.options.snap?(c=this.currentPage.pageX,d=this.currentPage.pageY,0<b?c--:0>b&&c++,0<a?d--:0>a&&d++,this.goToPage(c,d)):(c=this.x+e.round(this.hasHorizontalScroll?
b:0),d=this.y+e.round(this.hasVerticalScroll?a:0),this.directionX=0<b?-1:0>b?1:0,this.directionY=0<a?-1:0>a?1:0,0<c?c=0:c<this.maxScrollX&&(c=this.maxScrollX),0<d?d=0:d<this.maxScrollY&&(d=this.maxScrollY),this.scrollTo(c,d,0))}},_initSnap:function(){this.currentPage={};"string"==typeof this.options.snap&&(this.options.snap=this.scroller.querySelectorAll(this.options.snap));this.on("refresh",function(){var a=0,b,f=0,d,g,h,k=0,l;d=this.options.snapStepX||this.wrapperWidth;var n=this.options.snapStepY||
this.wrapperHeight,p;this.pages=[];if(this.wrapperWidth&&this.wrapperHeight&&this.scrollerWidth&&this.scrollerHeight){if(!0===this.options.snap)for(g=e.round(d/2),h=e.round(n/2);k>-this.scrollerWidth;){this.pages[a]=[];for(l=b=0;l>-this.scrollerHeight;)this.pages[a][b]={x:e.max(k,this.maxScrollX),y:e.max(l,this.maxScrollY),width:d,height:n,cx:k-g,cy:l-h},l-=n,b++;k-=d;a++}else for(n=this.options.snap,b=n.length,d=-1;a<b;a++){p=c.getRect(n[a]);if(0===a||p.left<=c.getRect(n[a-1]).left)f=0,d++;this.pages[f]||
(this.pages[f]=[]);k=e.max(-p.left,this.maxScrollX);l=e.max(-p.top,this.maxScrollY);g=k-e.round(p.width/2);h=l-e.round(p.height/2);this.pages[f][d]={x:k,y:l,width:p.width,height:p.height,cx:g,cy:h};k>this.maxScrollX&&f++}this.goToPage(this.currentPage.pageX||0,this.currentPage.pageY||0,0);0===this.options.snapThreshold%1?this.snapThresholdY=this.snapThresholdX=this.options.snapThreshold:(this.snapThresholdX=e.round(this.pages[this.currentPage.pageX][this.currentPage.pageY].width*this.options.snapThreshold),
this.snapThresholdY=e.round(this.pages[this.currentPage.pageX][this.currentPage.pageY].height*this.options.snapThreshold))}});this.on("flick",function(){var a=this.options.snapSpeed||e.max(e.max(e.min(e.abs(this.x-this.startX),1E3),e.min(e.abs(this.y-this.startY),1E3)),300);this.goToPage(this.currentPage.pageX+this.directionX,this.currentPage.pageY+this.directionY,a)})},_nearestSnap:function(a,b){if(!this.pages.length)return{x:0,y:0,pageX:0,pageY:0};var c=0,d=this.pages.length,g=0;if(e.abs(a-this.absStartX)<
this.snapThresholdX&&e.abs(b-this.absStartY)<this.snapThresholdY)return this.currentPage;0<a?a=0:a<this.maxScrollX&&(a=this.maxScrollX);0<b?b=0:b<this.maxScrollY&&(b=this.maxScrollY);for(;c<d;c++)if(a>=this.pages[c][0].cx){a=this.pages[c][0].x;break}for(d=this.pages[c].length;g<d;g++)if(b>=this.pages[0][g].cy){b=this.pages[0][g].y;break}c==this.currentPage.pageX&&(c+=this.directionX,0>c?c=0:c>=this.pages.length&&(c=this.pages.length-1),a=this.pages[c][0].x);g==this.currentPage.pageY&&(g+=this.directionY,
0>g?g=0:g>=this.pages[0].length&&(g=this.pages[0].length-1),b=this.pages[0][g].y);return{x:a,y:b,pageX:c,pageY:g}},goToPage:function(a,b,c,d){d=d||this.options.bounceEasing;a>=this.pages.length?a=this.pages.length-1:0>a&&(a=0);b>=this.pages[a].length?b=this.pages[a].length-1:0>b&&(b=0);var f=this.pages[a][b].x,h=this.pages[a][b].y;c=void 0===c?this.options.snapSpeed||e.max(e.max(e.min(e.abs(f-this.x),1E3),e.min(e.abs(h-this.y),1E3)),300):c;this.currentPage={x:f,y:h,pageX:a,pageY:b};this.scrollTo(f,
h,c,d)},next:function(a,b){var c=this.currentPage.pageX,d=this.currentPage.pageY;c++;c>=this.pages.length&&this.hasVerticalScroll&&(c=0,d++);this.goToPage(c,d,a,b)},prev:function(a,b){var c=this.currentPage.pageX,d=this.currentPage.pageY;c--;0>c&&this.hasVerticalScroll&&(c=0,d--);this.goToPage(c,d,a,b)},_initKeys:function(a){a={pageUp:33,pageDown:34,end:35,home:36,left:37,up:38,right:39,down:40};var b;if("object"==typeof this.options.keyBindings)for(b in this.options.keyBindings)"string"==typeof this.options.keyBindings[b]&&
(this.options.keyBindings[b]=this.options.keyBindings[b].toUpperCase().charCodeAt(0));else this.options.keyBindings={};for(b in a)this.options.keyBindings[b]=this.options.keyBindings[b]||a[b];c.addEvent(k,"keydown",this);this.on("destroy",function(){c.removeEvent(k,"keydown",this)})},_key:function(a){if(this.enabled){var b=this.options.snap,f=b?this.currentPage.pageX:this.x,d=b?this.currentPage.pageY:this.y,g=c.getTime(),h=this.keyTime||0,k;this.options.useTransition&&this.isInTransition&&(k=this.getComputedPosition(),
this._translate(e.round(k.x),e.round(k.y)),this.isInTransition=!1);this.keyAcceleration=200>g-h?e.min(this.keyAcceleration+.25,50):0;switch(a.keyCode){case this.options.keyBindings.pageUp:this.hasHorizontalScroll&&!this.hasVerticalScroll?f+=b?1:this.wrapperWidth:d+=b?1:this.wrapperHeight;break;case this.options.keyBindings.pageDown:this.hasHorizontalScroll&&!this.hasVerticalScroll?f-=b?1:this.wrapperWidth:d-=b?1:this.wrapperHeight;break;case this.options.keyBindings.end:f=b?this.pages.length-1:this.maxScrollX;
d=b?this.pages[0].length-1:this.maxScrollY;break;case this.options.keyBindings.home:d=f=0;break;case this.options.keyBindings.left:f+=b?-1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.up:d+=b?1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.right:f-=b?-1:5+this.keyAcceleration>>0;break;case this.options.keyBindings.down:d-=b?1:5+this.keyAcceleration>>0;break;default:return}b?this.goToPage(f,d):(0<f?this.keyAcceleration=f=0:f<this.maxScrollX&&(f=this.maxScrollX,this.keyAcceleration=
0),0<d?this.keyAcceleration=d=0:d<this.maxScrollY&&(d=this.maxScrollY,this.keyAcceleration=0),this.scrollTo(f,d,0),this.keyTime=g)}},_animate:function(a,b,e,d){function f(){var g=c.getTime(),m;g>=p?(h.isAnimating=!1,h._translate(a,b),h.resetPosition(h.options.bounceTime)||h._execEvent("scrollEnd")):(g=(g-n)/e,m=d(g),g=(a-k)*m+k,h._translate(g,(b-l)*m+l),h.isAnimating&&r(f))}var h=this,k=this.x,l=this.y,n=c.getTime(),p=n+e;this.isAnimating=!0;f()},handleEvent:function(a){switch(a.type){case "touchstart":case "pointerdown":case "MSPointerDown":case "mousedown":this._start(a);
break;case "touchmove":case "pointermove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "pointerup":case "MSPointerUp":case "mouseup":case "touchcancel":case "pointercancel":case "MSPointerCancel":case "mousecancel":this._end(a);break;case "orientationchange":case "resize":this._resize();break;case "transitionend":case "webkitTransitionEnd":case "oTransitionEnd":case "MSTransitionEnd":this._transitionEnd(a);break;case "wheel":case "DOMMouseScroll":case "mousewheel":this._wheel(a);
break;case "keydown":this._key(a);break;case "click":this.enabled&&!a._constructed&&(a.preventDefault(),a.stopPropagation())}}};u.prototype={handleEvent:function(a){switch(a.type){case "touchstart":case "pointerdown":case "MSPointerDown":case "mousedown":this._start(a);break;case "touchmove":case "pointermove":case "MSPointerMove":case "mousemove":this._move(a);break;case "touchend":case "pointerup":case "MSPointerUp":case "mouseup":case "touchcancel":case "pointercancel":case "MSPointerCancel":case "mousecancel":this._end(a)}},
destroy:function(){this.options.fadeScrollbars&&(clearTimeout(this.fadeTimeout),this.fadeTimeout=null);this.options.interactive&&(c.removeEvent(this.indicator,"touchstart",this),c.removeEvent(this.indicator,c.prefixPointerEvent("pointerdown"),this),c.removeEvent(this.indicator,"mousedown",this),c.removeEvent(k,"touchmove",this),c.removeEvent(k,c.prefixPointerEvent("pointermove"),this),c.removeEvent(k,"mousemove",this),c.removeEvent(k,"touchend",this),c.removeEvent(k,c.prefixPointerEvent("pointerup"),
this),c.removeEvent(k,"mouseup",this));this.options.defaultScrollbars&&this.wrapper.parentNode&&this.wrapper.parentNode.removeChild(this.wrapper)},_start:function(a){var b=a.touches?a.touches[0]:a;a.preventDefault();a.stopPropagation();this.transitionTime();this.initiated=!0;this.moved=!1;this.lastPointX=b.pageX;this.lastPointY=b.pageY;this.startTime=c.getTime();this.options.disableTouch||c.addEvent(k,"touchmove",this);this.options.disablePointer||c.addEvent(k,c.prefixPointerEvent("pointermove"),
this);this.options.disableMouse||c.addEvent(k,"mousemove",this);this.scroller._execEvent("beforeScrollStart")},_move:function(a){var b=a.touches?a.touches[0]:a,e,d;c.getTime();this.moved||this.scroller._execEvent("scrollStart");this.moved=!0;e=b.pageX-this.lastPointX;this.lastPointX=b.pageX;d=b.pageY-this.lastPointY;this.lastPointY=b.pageY;this._pos(this.x+e,this.y+d);a.preventDefault();a.stopPropagation()},_end:function(a){if(this.initiated){this.initiated=!1;a.preventDefault();a.stopPropagation();
c.removeEvent(k,"touchmove",this);c.removeEvent(k,c.prefixPointerEvent("pointermove"),this);c.removeEvent(k,"mousemove",this);if(this.scroller.options.snap){a=this.scroller._nearestSnap(this.scroller.x,this.scroller.y);var b=this.options.snapSpeed||e.max(e.max(e.min(e.abs(this.scroller.x-a.x),1E3),e.min(e.abs(this.scroller.y-a.y),1E3)),300);if(this.scroller.x!=a.x||this.scroller.y!=a.y)this.scroller.directionX=0,this.scroller.directionY=0,this.scroller.currentPage=a,this.scroller.scrollTo(a.x,a.y,
b,this.scroller.options.bounceEasing)}this.moved&&this.scroller._execEvent("scrollEnd")}},transitionTime:function(a){a=a||0;var b=c.style.transitionDuration;if(b&&(this.indicatorStyle[b]=a+"ms",!a&&c.isBadAndroid)){this.indicatorStyle[b]="0.0001ms";var e=this;r(function(){"0.0001ms"===e.indicatorStyle[b]&&(e.indicatorStyle[b]="0s")})}},transitionTimingFunction:function(a){this.indicatorStyle[c.style.transitionTimingFunction]=a},refresh:function(){this.transitionTime();this.indicatorStyle.display=
this.options.listenX&&!this.options.listenY?this.scroller.hasHorizontalScroll?"block":"none":this.options.listenY&&!this.options.listenX?this.scroller.hasVerticalScroll?"block":"none":this.scroller.hasHorizontalScroll||this.scroller.hasVerticalScroll?"block":"none";this.scroller.hasHorizontalScroll&&this.scroller.hasVerticalScroll?(c.addClass(this.wrapper,"iScrollBothScrollbars"),c.removeClass(this.wrapper,"iScrollLoneScrollbar"),this.options.defaultScrollbars&&this.options.customStyle&&(this.options.listenX?
this.wrapper.style.right="8px":this.wrapper.style.bottom="8px")):(c.removeClass(this.wrapper,"iScrollBothScrollbars"),c.addClass(this.wrapper,"iScrollLoneScrollbar"),this.options.defaultScrollbars&&this.options.customStyle&&(this.options.listenX?this.wrapper.style.right="2px":this.wrapper.style.bottom="2px"));c.getRect(this.wrapper);this.options.listenX&&(this.wrapperWidth=this.wrapper.clientWidth,this.options.resize?(this.indicatorWidth=e.max(e.round(this.wrapperWidth*this.wrapperWidth/(this.scroller.scrollerWidth||
this.wrapperWidth||1)),8),this.indicatorStyle.width=this.indicatorWidth+"px"):this.indicatorWidth=this.indicator.clientWidth,this.maxPosX=this.wrapperWidth-this.indicatorWidth,"clip"==this.options.shrink?(this.minBoundaryX=-this.indicatorWidth+8,this.maxBoundaryX=this.wrapperWidth-8):(this.minBoundaryX=0,this.maxBoundaryX=this.maxPosX),this.sizeRatioX=this.options.speedRatioX||this.scroller.maxScrollX&&this.maxPosX/this.scroller.maxScrollX);this.options.listenY&&(this.wrapperHeight=this.wrapper.clientHeight,
this.options.resize?(this.indicatorHeight=e.max(e.round(this.wrapperHeight*this.wrapperHeight/(this.scroller.scrollerHeight||this.wrapperHeight||1)),8),this.indicatorStyle.height=this.indicatorHeight+"px"):this.indicatorHeight=this.indicator.clientHeight,this.maxPosY=this.wrapperHeight-this.indicatorHeight,"clip"==this.options.shrink?(this.minBoundaryY=-this.indicatorHeight+8,this.maxBoundaryY=this.wrapperHeight-8):(this.minBoundaryY=0,this.maxBoundaryY=this.maxPosY),this.maxPosY=this.wrapperHeight-
this.indicatorHeight,this.sizeRatioY=this.options.speedRatioY||this.scroller.maxScrollY&&this.maxPosY/this.scroller.maxScrollY);this.updatePosition()},updatePosition:function(){var a=this.options.listenX&&e.round(this.sizeRatioX*this.scroller.x)||0,b=this.options.listenY&&e.round(this.sizeRatioY*this.scroller.y)||0;this.options.ignoreBoundaries||(a<this.minBoundaryX?("scale"==this.options.shrink&&(this.width=e.max(this.indicatorWidth+a,8),this.indicatorStyle.width=this.width+"px"),a=this.minBoundaryX):
a>this.maxBoundaryX?"scale"==this.options.shrink?(this.width=e.max(this.indicatorWidth-(a-this.maxPosX),8),this.indicatorStyle.width=this.width+"px",a=this.maxPosX+this.indicatorWidth-this.width):a=this.maxBoundaryX:"scale"==this.options.shrink&&this.width!=this.indicatorWidth&&(this.width=this.indicatorWidth,this.indicatorStyle.width=this.width+"px"),b<this.minBoundaryY?("scale"==this.options.shrink&&(this.height=e.max(this.indicatorHeight+3*b,8),this.indicatorStyle.height=this.height+"px"),b=this.minBoundaryY):
b>this.maxBoundaryY?"scale"==this.options.shrink?(this.height=e.max(this.indicatorHeight-3*(b-this.maxPosY),8),this.indicatorStyle.height=this.height+"px",b=this.maxPosY+this.indicatorHeight-this.height):b=this.maxBoundaryY:"scale"==this.options.shrink&&this.height!=this.indicatorHeight&&(this.height=this.indicatorHeight,this.indicatorStyle.height=this.height+"px"));this.x=a;this.y=b;this.scroller.options.useTransform?this.indicatorStyle[c.style.transform]="translate("+a+"px,"+b+"px)"+this.scroller.translateZ:
(this.indicatorStyle.left=a+"px",this.indicatorStyle.top=b+"px")},_pos:function(a,b){0>a?a=0:a>this.maxPosX&&(a=this.maxPosX);0>b?b=0:b>this.maxPosY&&(b=this.maxPosY);a=this.options.listenX?e.round(a/this.sizeRatioX):this.scroller.x;b=this.options.listenY?e.round(b/this.sizeRatioY):this.scroller.y;this.scroller.scrollTo(a,b)},fade:function(a,b){if(!b||this.visible)clearTimeout(this.fadeTimeout),this.fadeTimeout=null,b=a?0:300,this.wrapperStyle[c.style.transitionDuration]=(a?250:500)+"ms",this.fadeTimeout=
setTimeout(function(a){this.wrapperStyle.opacity=a;this.visible=+a}.bind(this,a?"1":"0"),b)}};q.utils=c;"undefined"!=typeof module&&module.exports?module.exports=q:"function"==typeof define&&define.amd?define(function(){return q}):k.IScroll=q})(window,document,Math);